yarnPath: .yarn/releases/yarn-sources.cjs
plugins:
  - ./commands/yarn/tsconfig-paths-plugin.js
  - ./commands/yarn/check-node-version.js
# test comment
packageExtensions:
  ilp-packet@*:
    dependencies:
      long: "*"
  ilp-protocol-stream@*:
    dependencies:
      "@types/long": "*"
  inversify-logger-middleware@*:
    dependencies:
      inversify: "*"
  react-hot-loader@*:
    dependencies:
      "@hot-loader/react-dom": "*"
  inversify-express-utils@*:
    dependencies:
      "@types/express": "*"
      inversify: "*"
