# set to "node-modules" if need to edit 3rd party
# dependencies for debugging purposes
nodeLinker: pnp

packageExtensions:
  ilp-packet@*:
    dependencies:
      long: "*"
  ilp-protocol-stream@*:
    dependencies:
      "@types/long": "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"
  inversify-express-utils@*:
    dependencies:
      "@types/express": "*"
      inversify: "*"
  inversify-logger-middleware@*:
    dependencies:
      inversify: "*"
  react-hot-loader@*:
    dependencies:
      "@hot-loader/react-dom": "*"

plugins:
  - ./commands/yarn/tsconfig-paths-plugin.js
  - ./commands/yarn/check-node-version.js

yarnPath: .yarn/releases/yarn-2.4.0.cjs
